if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

LOGFILE=~/bash_boost.log
cat > $LOGFILE <<< "--- Attempting to boost your bash non login..."

cat >> $LOGFILE <<< "history boost..."
source ~/.history

cat >> $LOGFILE <<< "aliases..."
source ~/.aliases

cat >> $LOGFILE <<< "environment..."
source ~/.os_specific/loader

cat >> $LOGFILE <<< "user specific boost..."
source ~/.user_specific/loader

cat >> $LOGFILE <<< "--- Boost process for non login shell Complete!"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

### Java stuff
export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk-13.jdk/Contents/Home/
export GRADLE_HOME=/usr/local/Cellar/gradle/2.3/libexec

# added by travis gem
[ -f /Users/rouan/.travis/travis.sh ] && source /Users/rouan/.travis/travis.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
